runtime: nodejs18

env_variables:
  # Application
  NAME: 'api-dizimo'
  VERSION: '1.0.0'
  NODE_ENV: 'develop'
  DB_CONNECTION_STRING: 'postgresql://postgres:C0mp@nhi@deJesus@34.95.144.108:5432/immaculata'